from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE

from app.core.deliverable import DeliverableMetadata, IDeliverable
from app.services.deliverable_quality import _validate_pptx_completeness

logger = logging.getLogger(__name__)


class PPTXDeliverable(IDeliverable):
    """PPTX presentation deliverable implementation.

    Extracted from storage.py _write_pptx_output() with full slide type support
    (title, bullets, stat_cards, column_cards, stack_layers, table, chart, section_divider).
    """

    # Brand design tokens (from storage.py _B dict)
    BRAND_COLORS = {
        "green":       RGBColor(0x86, 0xBC, 0x25),
        "dark":        RGBColor(0x1A, 0x1A, 0x1A),
        "mid_dark":    RGBColor(0x2D, 0x2D, 0x2D),
        "mid":         RGBColor(0x3D, 0x3D, 0x3D),
        "dark_green":  RGBColor(0x5A, 0x8A, 0x00),
        "gray":        RGBColor(0x75, 0x78, 0x7B),
        "light_gray":  RGBColor(0xAA, 0xAA, 0xAA),
        "white":       RGBColor(0xFF, 0xFF, 0xFF),
        "light_green": RGBColor(0xEB, 0xF5, 0xD3),
        "e8":          RGBColor(0xE8, 0xE8, 0xE8),
    }

    FONT_NAME = "Calibri"

    LAYOUT_COMPAT = {
        "title_content":    "bullets",
        "title_and_content":"bullets",
        "title_only":       "bullets",
        "two_content":      "column_cards",
        "blank":            "bullets",
    }

    def get_metadata(self) -> DeliverableMetadata:
        return DeliverableMetadata(
            output_type="pptx",
            file_extension=".pptx",
            mime_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            intermediate_format="json",
            skill_output_key="pptx_slides",
        )

    def render(self, payload: dict[str, Any], run_dir: Path, branding: Any | None = None) -> Path | None:
        """Render PPTX presentation from payload.

        Args:
            payload: Agent output with pptx_slides key
            run_dir: Directory to save output PPTX
            branding: Optional branding configuration

        Returns:
            Path to generated PPTX file, or None if failed
        """
        out = run_dir / "output.pptx"

        try:
            prs = Presentation()
            prs.slide_width = Inches(10.0)
            prs.slide_height = Inches(5.625)

            slides = payload.get("pptx_slides")
            if not (isinstance(slides, list) and slides):
                # Minimal fallback
                slides = [
                    {"title": "Process Output", "slide_type": "title", "subtitle": "Generated by ProcessDoc Studio"},
                    {"title": "Summary", "slide_type": "bullets", "bullets": [
                        self._safe_text(payload.get("narrative_md"), "No content generated")[:120],
                    ]},
                ]

            # Validate completeness
            is_complete, issues = _validate_pptx_completeness(json.dumps(payload.get("pptx_slides", [])))
            if not is_complete:
                logger.warning(f"PPTX completeness issues: {issues}")

            total = min(len(slides), 20)
            for page_num, item in enumerate(slides[:20], start=1):
                if not isinstance(item, dict):
                    continue

                # Resolve slide_type — support legacy "layout" field for backward compat
                slide_type = str(item.get("slide_type") or "").strip()
                if not slide_type:
                    legacy = str(item.get("layout") or "").strip().lower().replace("-", "_")
                    slide_type = self.LAYOUT_COMPAT.get(legacy, "bullets")
                    if slide_type == "bullets" and item.get("table"):
                        slide_type = "table"
                    elif slide_type == "bullets" and item.get("chart"):
                        slide_type = "chart"

                if slide_type == "title":
                    self._render_title_slide(prs, item)
                else:
                    self._render_content_slide(prs, item, page_num, total, slide_type)

            prs.save(out)
            logger.info(f"PPTX rendered successfully: {out}")
            return out

        except Exception as e:
            logger.error(f"Failed to render PPTX: {e}", exc_info=True)
            return None

    def validate(self, data: dict[str, Any]) -> tuple[bool, list[str]]:
        """Check PPTX completeness."""
        pptx_str = json.dumps(data) if isinstance(data, (dict, list)) else str(data)
        return _validate_pptx_completeness(pptx_str)

    def extract_quality_signals(self, artifact_path: Path) -> dict[str, Any]:
        try:
            prs = Presentation(str(artifact_path))
            slide_count = len(prs.slides)
            title_count = 0
            text_chars = 0
            for slide in prs.slides:
                for shape in slide.shapes:
                    if hasattr(shape, "text") and isinstance(shape.text, str):
                        txt = shape.text.strip()
                        if txt:
                            text_chars += len(txt)
                            if len(txt) <= 80:
                                title_count += 1
            return {
                "slide_count": slide_count,
                "text_chars": text_chars,
                "title_like_blocks": title_count,
                "artifact_path": str(artifact_path),
            }
        except Exception as e:
            logger.error(f"Failed to extract quality signals: {e}")
            return super().extract_quality_signals(artifact_path)

    # ── Helper methods ────────────────────────────────────────────────────

    def _safe_text(self, value: object, default: str = "") -> str:
        """Safely convert value to text."""
        return str(value or default).strip()

    def _rgb(self, token: str) -> RGBColor:
        """Get RGB color from brand token."""
        return self.BRAND_COLORS.get(str(token).lower(), self.BRAND_COLORS["mid"])

    def _add_rect(self, slide: Any, x: float, y: float, w: float, h: float, color_token: str) -> Any:
        """Add rectangle shape to slide."""
        shape = slide.shapes.add_shape(1, Inches(x), Inches(y), Inches(w), Inches(h))
        fill = shape.fill
        fill.solid()
        fill.fore_color.rgb = self._rgb(color_token)
        shape.line.fill.background()
        return shape

    def _add_text(
        self, slide: Any, x: float, y: float, w: float, h: float,
        text: str, size: float, color_token: str,
        bold: bool = False, align: str = "left",
    ) -> Any:
        """Add text box to slide."""
        txb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
        tf = txb.text_frame
        tf.word_wrap = True
        tf.auto_size = None
        p = tf.paragraphs[0]
        p.alignment = (
            PP_ALIGN.CENTER if align == "center" else
            (PP_ALIGN.RIGHT if align == "right" else PP_ALIGN.LEFT)
        )
        run = p.add_run()
        run.text = self._safe_text(text, "")
        run.font.name = self.FONT_NAME
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = self._rgb(color_token)
        return txb

    def _add_chrome(self, slide: Any, title: str, page_num: int, total: int) -> None:
        """Add page chrome (header, footer, branding)."""
        self._add_rect(slide, 0.0, 0.0, 10.0, 0.07, "green")
        self._add_rect(slide, 0.0, 0.07, 0.06, 5.55, "dark")
        self._add_text(slide, 0.28, 0.18, 8.50, 0.60, title, 22, "dark", bold=True)
        self._add_text(slide, 8.80, 5.30, 1.00, 0.25, f"{page_num} / {total}", 9, "light_gray")
        self._add_text(slide, 0.18, 5.30, 1.50, 0.25, "Deloitte.", 10, "gray", bold=True)

    def _blank_slide(self, prs: Any) -> Any:
        """Create blank slide."""
        layouts = prs.slide_layouts
        return prs.slides.add_slide(layouts[6] if len(layouts) > 6 else layouts[-1])

    def _render_footer_note(self, slide: Any, note: str) -> None:
        """Render footer note on slide."""
        self._add_rect(slide, 0.28, 5.22, 9.44, 0.26, "light_green")
        self._add_text(slide, 0.38, 5.22, 9.24, 0.26, note, 9, "mid")

    # ── Slide renderers ────────────────────────────────────────────────────

    def _render_title_slide(self, prs: Any, item: dict[str, Any]) -> None:
        """Render title slide."""
        slide = self._blank_slide(prs)
        self._add_rect(slide, 0.0,  0.0,   0.35, 5.625, "green")
        self._add_rect(slide, 0.0,  5.35, 10.0,  0.28,  "green")
        self._add_text(slide, 0.60, 0.40,  3.00, 0.50, "Deloitte.", 20, "white", bold=True)
        title_text = self._safe_text(item.get("title"), "Process Overview")
        self._add_text(slide, 0.60, 1.15, 8.80, 1.05, title_text, 44, "white", bold=True)
        self._add_rect(slide, 0.60, 2.28, 5.50, 0.06, "green")
        subtitle = self._safe_text(item.get("subtitle"), "Executive Presentation")
        self._add_text(slide, 0.60, 2.48, 8.80, 0.55, subtitle, 18, "light_gray")
        badges = item.get("badges") if isinstance(item.get("badges"), list) else []
        xs = [0.60, 3.80]
        y_start = 3.22
        for i, badge in enumerate(badges[:4]):
            col = i % 2
            row = i // 2
            x = xs[col]
            y = y_start + row * 0.65
            badge_text = self._safe_text(badge)
            if badge_text:
                self._add_rect(slide, x, y, 3.00, 0.55, "mid")
                self._add_text(slide, x + 0.15, y + 0.05, 2.70, 0.45, badge_text, 13, "white")
        footer = self._safe_text(item.get("footer"), "")
        if footer:
            self._render_footer_note(slide, footer)

    def _render_content_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int, slide_type: str) -> None:
        """Dispatch to appropriate content slide renderer."""
        renderers = {
            "bullets":          self._render_bullets_slide,
            "stat_cards":       self._render_stat_cards_slide,
            "column_cards":     self._render_column_cards_slide,
            "stack_layers":     self._render_stack_layers_slide,
            "table":            self._render_table_slide,
            "chart":            self._render_chart_slide,
            "section_divider":  self._render_section_divider_slide,
        }
        renderer = renderers.get(slide_type, self._render_bullets_slide)
        renderer(prs, item, page_num, total)

    def _render_bullets_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render bullets slide."""
        slide = self._blank_slide(prs)
        self._add_chrome(slide, self._safe_text(item.get("title"), ""), page_num, total)
        bullets = item.get("bullets") if isinstance(item.get("bullets"), list) else []

        n = len(bullets)
        if n <= 3:
            font_size, max_chars = 16, 140
        elif n <= 5:
            font_size, max_chars = 14, 120
        elif n <= 8:
            font_size, max_chars = 12, 100
        else:
            font_size, max_chars = 10, 80

        validated_bullets = []
        for i, bullet in enumerate(bullets[:12]):
            bullet_text = self._safe_text(bullet)
            if len(bullet_text) > max_chars:
                logger.warning(
                    f"Bullet {i} on '{item.get('title')}' exceeds {max_chars} chars (got {len(bullet_text)})"
                )
                bullet_text = bullet_text[:max_chars - 3] + "..."
            validated_bullets.append(bullet_text)

        if validated_bullets:
            txb = slide.shapes.add_textbox(Inches(0.28), Inches(0.95), Inches(9.44), Inches(4.5))
            tf = txb.text_frame
            tf.word_wrap = True
            for i, bullet_text in enumerate(validated_bullets):
                p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                p.alignment = PP_ALIGN.LEFT
                p.level = 0
                run = p.add_run()
                run.text = bullet_text
                run.font.name = self.FONT_NAME
                run.font.size = Pt(font_size)
                run.font.color.rgb = self._rgb("dark")

        # Check for footer_note or footer (support both for compatibility)
        footer = self._safe_text(item.get("footer_note") or item.get("footer"), "")
        if footer:
            self._render_footer_note(slide, footer)

    def _render_stat_cards_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render stat cards slide."""
        slide = self._blank_slide(prs)
        self._add_chrome(slide, self._safe_text(item.get("title"), ""), page_num, total)
        cards = item.get("stat_cards") if isinstance(item.get("stat_cards"), list) else []
        if not cards:
            logger.warning(
                f"Slide '{item.get('title')}' (stat_cards): expected 3+, got {len(cards)}"
            )
            return

        card_w = 3.02
        card_h = 1.8
        padding_x = 0.28
        padding_y = 0.95
        spacing_x = 0.14
        spacing_y = 0.14

        for i, card in enumerate(cards[:6]):
            row = i // 3
            col = i % 3
            x = padding_x + col * (card_w + spacing_x)
            y = padding_y + row * (card_h + spacing_y)

            fill_token = card.get("fill", "mid_dark")
            self._add_rect(slide, x, y, card_w, card_h, fill_token)

            stat = self._safe_text(card.get("stat"), "—")
            label = self._safe_text(card.get("label"), "")
            desc = self._safe_text(card.get("description"), "")[:60]

            self._add_text(slide, x + 0.15, y + 0.20, card_w - 0.30, 0.50, stat, 18, "white", bold=True)
            self._add_text(slide, x + 0.15, y + 0.75, card_w - 0.30, 0.35, label, 11, "white", bold=True)
            self._add_text(slide, x + 0.15, y + 1.15, card_w - 0.30, 0.55, desc, 9, "light_gray")

    def _render_column_cards_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render column cards slide."""
        slide = self._blank_slide(prs)
        self._add_chrome(slide, self._safe_text(item.get("title"), ""), page_num, total)
        cards = item.get("column_cards") if isinstance(item.get("column_cards"), list) else []
        if not cards:
            logger.warning(
                f"Slide '{item.get('title')}' (column_cards): expected 3+, got {len(cards)}"
            )
            return

        col_w = 3.0
        col_h = 4.0
        col_padding_x = 0.28
        col_padding_y = 0.95
        col_spacing = 0.16

        for i, card in enumerate(cards[:3]):
            x = col_padding_x + i * (col_w + col_spacing)
            y = col_padding_y

            accent = card.get("accent", "mid")
            self._add_rect(slide, x, y, col_w, col_h, accent)

            heading = self._safe_text(card.get("heading"), "")
            body = self._safe_text(card.get("body"), "")

            self._add_text(slide, x + 0.20, y + 0.25, col_w - 0.40, 0.40, heading, 14, "white", bold=True)
            self._add_text(slide, x + 0.20, y + 0.75, col_w - 0.40, 3.0, body, 11, "white")

    def _render_stack_layers_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render stacked layers slide."""
        slide = self._blank_slide(prs)
        self._add_chrome(slide, self._safe_text(item.get("title"), ""), page_num, total)
        layers = item.get("stack_layers") if isinstance(item.get("stack_layers"), list) else []
        if not layers:
            logger.warning(
                f"Slide '{item.get('title')}' (stack_layers): expected 1+, got {len(layers)}"
            )
            return

        layer_height = 3.6 / len(layers)
        start_y = 0.95

        for i, layer in enumerate(layers[:6]):
            y = start_y + i * layer_height
            # Support both "fill" and "color" for compatibility
            color = layer.get("fill") or layer.get("color") or "mid"
            label = self._safe_text(layer.get("label"), f"Layer {i+1}")
            description = self._safe_text(layer.get("description"), "")

            self._add_rect(slide, 0.28, y, 9.44, layer_height - 0.05, color)
            self._add_text(slide, 0.50, y + 0.15, 4.0, 0.40, label, 14, "white", bold=True)
            if description:
                self._add_text(slide, 0.50, y + 0.60, 8.94, 0.35, description, 10, "light_gray")

    def _render_table_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render table slide."""
        slide = self._blank_slide(prs)
        self._add_chrome(slide, self._safe_text(item.get("title"), ""), page_num, total)

        table_data = item.get("table", {})
        rows = table_data.get("rows", []) if isinstance(table_data, dict) else []

        if not rows:
            logger.warning(
                f"Slide '{item.get('title')}' (table): expected 1+ rows, got {len(rows)}"
            )
            return

        headers = table_data.get("headers", []) if isinstance(table_data, dict) else []
        num_cols = len(headers) if headers else (len(rows[0]) if rows else 1)
        num_rows = len(rows) + (1 if headers else 0)

        if num_cols > 0 and num_rows > 0:
            # Get table position and dimensions
            x = float(table_data.get("x", 0.28)) if isinstance(table_data, dict) else 0.28
            y = float(table_data.get("y", 1.0)) if isinstance(table_data, dict) else 1.0
            w = float(table_data.get("w", 9.44)) if isinstance(table_data, dict) else 9.44
            h = float(table_data.get("h", 3.5)) if isinstance(table_data, dict) else 3.5

            # Create table shape with proper dimensions
            shape = slide.shapes.add_table(num_rows, num_cols, Inches(x), Inches(y), Inches(w), Inches(h))
            tbl = shape.table

            # Fill in headers if present
            if headers:
                for col_idx, header in enumerate(headers[:num_cols]):
                    cell = tbl.cell(0, col_idx)
                    cell.text = str(header).strip()
                    # Style header cell
                    for paragraph in cell.text_frame.paragraphs:
                        paragraph.font.bold = True
                        paragraph.font.color.rgb = self._rgb("dark")

            # Fill in data rows
            for row_idx, row in enumerate(rows[:12]):
                actual_row = row_idx + (1 if headers else 0)
                if isinstance(row, list):
                    for col_idx, cell_value in enumerate(row[:num_cols]):
                        cell = tbl.cell(actual_row, col_idx)
                        cell.text = str(cell_value).strip()[:50]
                        for paragraph in cell.text_frame.paragraphs:
                            paragraph.font.color.rgb = self._rgb("dark")

    def _render_chart_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render chart slide with actual chart object."""
        slide = self._blank_slide(prs)
        self._add_chrome(slide, self._safe_text(item.get("title"), ""), page_num, total)

        chart_data_dict = item.get("chart", {})
        if not isinstance(chart_data_dict, dict):
            return

        # Get chart dimensions
        x = float(chart_data_dict.get("x", 0.8)) if chart_data_dict.get("x") else 0.8
        y = float(chart_data_dict.get("y", 1.4)) if chart_data_dict.get("y") else 1.4
        w = float(chart_data_dict.get("w", 8.5)) if chart_data_dict.get("w") else 8.5
        h = float(chart_data_dict.get("h", 3.5)) if chart_data_dict.get("h") else 3.5

        try:
            # Determine chart type
            chart_type_str = str(chart_data_dict.get("type", "line")).lower()
            chart_type_map = {
                "line": XL_CHART_TYPE.LINE,
                "column": XL_CHART_TYPE.COLUMN_CLUSTERED,
                "bar": XL_CHART_TYPE.BAR_CLUSTERED,
                "pie": XL_CHART_TYPE.PIE,
            }
            chart_type = chart_type_map.get(chart_type_str, XL_CHART_TYPE.LINE)

            # Build chart data
            categories = chart_data_dict.get("categories", ["A", "B", "C"])
            series_list = chart_data_dict.get("series", [{"name": "Series 1", "values": [1, 2, 3]}])

            chart_data = CategoryChartData()
            chart_data.categories = categories

            for series_dict in series_list:
                if isinstance(series_dict, dict):
                    series_name = str(series_dict.get("name", "Series")).strip()
                    values = series_dict.get("values", [1, 2, 3])
                    if isinstance(values, list):
                        chart_data.add_series(series_name, tuple(values))

            # Add chart to slide
            slide.shapes.add_chart(chart_type, Inches(x), Inches(y), Inches(w), Inches(h), chart_data)

        except Exception as e:
            logger.warning(f"Failed to render chart on slide '{item.get('title')}': {e}")
            # Fallback: render as text
            desc = self._safe_text(item.get("description"), f"A {chart_data_dict.get('type', 'chart')} chart")
            self._add_text(slide, 0.50, 1.5, 9.0, 3.5, desc, 14, "dark")

    def _render_section_divider_slide(self, prs: Any, item: dict[str, Any], page_num: int, total: int) -> None:
        """Render section divider slide."""
        slide = self._blank_slide(prs)
        self._add_rect(slide, 0.0, 0.0, 10.0, 5.625, "dark")

        title = self._safe_text(item.get("title"), "New Section")
        self._add_text(slide, 0.60, 2.0, 8.80, 1.0, title, 40, "white", bold=True, align="center")

        subtitle = self._safe_text(item.get("subtitle"), "")
        if subtitle:
            self._add_text(slide, 0.60, 3.2, 8.80, 0.6, subtitle, 18, "light_green", align="center")

